// Code generated by "stringer -type=ObjectType --linecomment"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Type-0]
	_ = x[TupleType-1]
	_ = x[BuiltinType-2]
	_ = x[FunctionType-3]
	_ = x[HashMapType-4]
	_ = x[ArrayType-5]
	_ = x[StringType-6]
	_ = x[IntegerType-7]
	_ = x[BooleanType-8]
	_ = x[ReturnType-9]
	_ = x[ErrorType-10]
	_ = x[NullType-11]
}

const _ObjectType_name = "TypeTupleBuiltinFunctionHashMapArrayStringIntegerBooleanReturnErrorNull"

var _ObjectType_index = [...]uint8{0, 4, 9, 16, 24, 31, 36, 42, 49, 56, 62, 67, 71}

func (i ObjectType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ObjectType_index)-1 {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[idx]:_ObjectType_index[idx+1]]
}
