// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Ident-2]
	_ = x[String-3]
	_ = x[Int-4]
	_ = x[Comma-5]
	_ = x[Colon-6]
	_ = x[Semicolon-7]
	_ = x[LParen-8]
	_ = x[RParen-9]
	_ = x[LBrace-10]
	_ = x[RBrace-11]
	_ = x[LBracket-12]
	_ = x[RBracket-13]
	_ = x[Assign-14]
	_ = x[Plus-15]
	_ = x[Minus-16]
	_ = x[Bang-17]
	_ = x[Asterisk-18]
	_ = x[Slash-19]
	_ = x[LT-20]
	_ = x[GT-21]
	_ = x[Eq-22]
	_ = x[NotEq-23]
	_ = x[And-24]
	_ = x[Or-25]
	_ = x[Pipe-26]
	_ = x[Function-27]
	_ = x[Let-28]
	_ = x[True-29]
	_ = x[False-30]
	_ = x[If-31]
	_ = x[Else-32]
	_ = x[Return-33]
}

const _TokenType_name = "IllegalEOFIdentStringIntCommaColonSemicolonLParenRParenLBraceRBraceLBracketRBracketAssignPlusMinusBangAsteriskSlashLTGTEqNotEqAndOrPipeFunctionLetTrueFalseIfElseReturn"

var _TokenType_index = [...]uint8{0, 7, 10, 15, 21, 24, 29, 34, 43, 49, 55, 61, 67, 75, 83, 89, 93, 98, 102, 110, 115, 117, 119, 121, 126, 129, 131, 135, 143, 146, 150, 155, 157, 161, 167}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
