// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Ident-2]
	_ = x[String-3]
	_ = x[Int-4]
	_ = x[Comma-5]
	_ = x[Semicolon-6]
	_ = x[LParen-7]
	_ = x[RParen-8]
	_ = x[LBrace-9]
	_ = x[RBrace-10]
	_ = x[LBracket-11]
	_ = x[RBracket-12]
	_ = x[Assign-13]
	_ = x[Plus-14]
	_ = x[Minus-15]
	_ = x[Bang-16]
	_ = x[Asterisk-17]
	_ = x[Slash-18]
	_ = x[LT-19]
	_ = x[GT-20]
	_ = x[Eq-21]
	_ = x[NotEq-22]
	_ = x[And-23]
	_ = x[Or-24]
	_ = x[Function-25]
	_ = x[Let-26]
	_ = x[True-27]
	_ = x[False-28]
	_ = x[If-29]
	_ = x[Else-30]
	_ = x[Return-31]
}

const _TokenType_name = "IllegalEOFIdentStringIntCommaSemicolonLParenRParenLBraceRBraceLBracketRBracketAssignPlusMinusBangAsteriskSlashLTGTEqNotEqAndOrFunctionLetTrueFalseIfElseReturn"

var _TokenType_index = [...]uint8{0, 7, 10, 15, 21, 24, 29, 38, 44, 50, 56, 62, 70, 78, 84, 88, 93, 97, 105, 110, 112, 114, 116, 121, 124, 126, 134, 137, 141, 146, 148, 152, 158}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
